version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    networks:
      - ruc-detect

  gradio:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -c "pip install gradio requests && python app.py"
    environment:
      - SPACE_API_URL=http://api:8000
    ports:
      - "7860:7860"
    depends_on:
      - api
    networks:
      - ruc-detect

networks:
  ruc-detect:
    driver: bridge
