name: ruc-detect
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - cpuonly
  - pip
  - pip:
    - gradio>=4.0.0
    - pandas
    - fastapi>=0.109.0
    - pydantic>=2.0.0
    - slowapi
    - uvicorn
    - sentence-transformers>=2.3.0
    - transformers>=4.36.0
    - faiss-cpu>=1.7.4
    - numpy
    - scikit-learn
    - matplotlib
    - seaborn
    - datasets
    - spacy
    - structlog
    - accelerate
    - requests
    - ruff
